#ifndef PXGL_GLFUNCTIONS_HPP
#define PXGL_GLFUNCTIONS_HPP

#include <Windows.h>
#include <include/px.hpp>
#include <gl/GL.h>
#include "glext.h"


#define PXGL_GLFUNCTION(name, prototype) prototype name ## _;

#define PXGL_GLFUNCTIONINSTALL(name, prototype) name ## _ = (prototype)wglGetProcAddress(#name);

//\
//if (!name ## _)\
//{\
//	px::Exception e(px::ErrorID::DisplayDriverError);\
//	e[px::ErrorTag::Function] = AxW::Str(#name);\
//	throw e;\
//}

namespace pxgl
{
	class GLFunctions
	{
	public:

		PXGL_GLFUNCTION(glCreateProgram, PFNGLCREATEPROGRAMPROC)
		PXGL_GLFUNCTION(glDeleteProgram, PFNGLDELETEPROGRAMPROC)
		PXGL_GLFUNCTION(glBindVertexArray, PFNGLBINDVERTEXARRAYPROC)
		PXGL_GLFUNCTION(glBindBuffer, PFNGLBINDBUFFERPROC)
		PXGL_GLFUNCTION(glBufferData, PFNGLBUFFERDATAPROC)
		PXGL_GLFUNCTION(glGenBuffers, PFNGLGENBUFFERSPROC)
		PXGL_GLFUNCTION(glDeleteBuffers, PFNGLDELETEBUFFERSPROC)
		PXGL_GLFUNCTION(glGenVertexArrays, PFNGLGENVERTEXARRAYSPROC)
		PXGL_GLFUNCTION(glDeleteVertexArrays, PFNGLDELETEVERTEXARRAYSPROC)
		PXGL_GLFUNCTION(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAYPROC)
		PXGL_GLFUNCTION(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTERPROC)
		PXGL_GLFUNCTION(glCreateShader, PFNGLCREATESHADERPROC)
		PXGL_GLFUNCTION(glDeleteShader, PFNGLDELETESHADERPROC)
		PXGL_GLFUNCTION(glShaderSource, PFNGLSHADERSOURCEPROC)
		PXGL_GLFUNCTION(glCompileShader, PFNGLCOMPILESHADERPROC)
		PXGL_GLFUNCTION(glGetShaderiv, PFNGLGETSHADERIVPROC)
		PXGL_GLFUNCTION(glGetShaderInfoLog, PFNGLGETSHADERINFOLOGPROC)
		PXGL_GLFUNCTION(glAttachShader, PFNGLATTACHSHADERPROC)
		PXGL_GLFUNCTION(glDetachShader, PFNGLDETACHSHADERPROC)
		PXGL_GLFUNCTION(glLinkProgram, PFNGLLINKPROGRAMPROC)
		PXGL_GLFUNCTION(glGetProgramiv, PFNGLGETPROGRAMIVPROC)
		PXGL_GLFUNCTION(glGetProgramInfoLog, PFNGLGETPROGRAMINFOLOGPROC)
		PXGL_GLFUNCTION(glUseProgram, PFNGLUSEPROGRAMPROC)
		PXGL_GLFUNCTION(glGenFramebuffers, PFNGLGENFRAMEBUFFERSPROC)
		PXGL_GLFUNCTION(glBindFramebuffer, PFNGLBINDFRAMEBUFFERPROC)
		PXGL_GLFUNCTION(glFramebufferTexture, PFNGLFRAMEBUFFERTEXTUREPROC)
		PXGL_GLFUNCTION(glDrawBuffers, PFNGLDRAWBUFFERSPROC)
		PXGL_GLFUNCTION(glCheckFramebufferStatus, PFNGLCHECKFRAMEBUFFERSTATUSPROC)
		PXGL_GLFUNCTION(glClearBufferfv, PFNGLCLEARBUFFERFVPROC)
		PXGL_GLFUNCTION(glBlendEquation, PFNGLBLENDEQUATIONPROC)

		PXGL_GLFUNCTION(glUniformMatrix4dv, PFNGLUNIFORMMATRIX4DVPROC)
		PXGL_GLFUNCTION(glUniformMatrix4fv, PFNGLUNIFORMMATRIX4FVPROC)
		PXGL_GLFUNCTION(glUniform4f, PFNGLUNIFORM4FPROC)
		PXGL_GLFUNCTION(glUniform3f, PFNGLUNIFORM3FPROC)
		PXGL_GLFUNCTION(glUniform2f, PFNGLUNIFORM2FPROC)
		PXGL_GLFUNCTION(glUniform1i, PFNGLUNIFORM1IPROC)
		PXGL_GLFUNCTION(glUniform1f, PFNGLUNIFORM1FPROC)
		PXGL_GLFUNCTION(glUniform3fv, PFNGLUNIFORM3FVPROC)
		PXGL_GLFUNCTION(glGetUniformLocation, PFNGLGETUNIFORMLOCATIONPROC)

		PXGL_GLFUNCTION(glBufferSubData, PFNGLBUFFERSUBDATAPROC)
		PXGL_GLFUNCTION(glBindBufferBase, PFNGLBINDBUFFERBASEPROC)

		PXGL_GLFUNCTION(glActiveTexture, PFNGLACTIVETEXTUREPROC)
		PXGL_GLFUNCTION(glDebugMessageCallback, PFNGLDEBUGMESSAGECALLBACKPROC)

		PXGL_GLFUNCTION(glGetIntegeri_v, PFNGLGETINTEGERI_VPROC)
		PXGL_GLFUNCTION(glTexBuffer, PFNGLTEXBUFFERPROC)
		PXGL_GLFUNCTION(glGetBufferSubData, PFNGLGETBUFFERSUBDATAPROC)
		PXGL_GLFUNCTION(glDispatchCompute, PFNGLDISPATCHCOMPUTEPROC)
		PXGL_GLFUNCTION(glMemoryBarrier, PFNGLMEMORYBARRIERPROC)
		PXGL_GLFUNCTION(glBindImageTexture, PFNGLBINDIMAGETEXTUREPROC)
		PXGL_GLFUNCTION(glDeleteFramebuffers, PFNGLDELETEFRAMEBUFFERSPROC)

		PXGL_GLFUNCTION(glGetGraphicsResetStatus, PFNGLGETGRAPHICSRESETSTATUSPROC)


		GLFunctions()
		{
			PXGL_GLFUNCTIONINSTALL(glCreateProgram, PFNGLCREATEPROGRAMPROC)
			PXGL_GLFUNCTIONINSTALL(glDeleteProgram, PFNGLDELETEPROGRAMPROC)
			PXGL_GLFUNCTIONINSTALL(glBindVertexArray, PFNGLBINDVERTEXARRAYPROC)
			PXGL_GLFUNCTIONINSTALL(glBindBuffer, PFNGLBINDBUFFERPROC)
			PXGL_GLFUNCTIONINSTALL(glBufferData, PFNGLBUFFERDATAPROC)
			PXGL_GLFUNCTIONINSTALL(glGenBuffers, PFNGLGENBUFFERSPROC)
			PXGL_GLFUNCTIONINSTALL(glDeleteBuffers, PFNGLDELETEBUFFERSPROC)
			PXGL_GLFUNCTIONINSTALL(glGenVertexArrays, PFNGLGENVERTEXARRAYSPROC)
			PXGL_GLFUNCTIONINSTALL(glDeleteVertexArrays, PFNGLDELETEVERTEXARRAYSPROC)
			PXGL_GLFUNCTIONINSTALL(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAYPROC)
			PXGL_GLFUNCTIONINSTALL(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTERPROC)
			PXGL_GLFUNCTIONINSTALL(glCreateShader, PFNGLCREATESHADERPROC)
			PXGL_GLFUNCTIONINSTALL(glDeleteShader, PFNGLDELETESHADERPROC)
			PXGL_GLFUNCTIONINSTALL(glShaderSource, PFNGLSHADERSOURCEPROC)
			PXGL_GLFUNCTIONINSTALL(glCompileShader, PFNGLCOMPILESHADERPROC)
			PXGL_GLFUNCTIONINSTALL(glGetShaderiv, PFNGLGETSHADERIVPROC)
			PXGL_GLFUNCTIONINSTALL(glGetShaderInfoLog, PFNGLGETSHADERINFOLOGPROC)
			PXGL_GLFUNCTIONINSTALL(glAttachShader, PFNGLATTACHSHADERPROC)
			PXGL_GLFUNCTIONINSTALL(glDetachShader, PFNGLDETACHSHADERPROC)
			PXGL_GLFUNCTIONINSTALL(glLinkProgram, PFNGLLINKPROGRAMPROC)
			PXGL_GLFUNCTIONINSTALL(glGetProgramiv, PFNGLGETPROGRAMIVPROC)
			PXGL_GLFUNCTIONINSTALL(glGetProgramInfoLog, PFNGLGETPROGRAMINFOLOGPROC)
			PXGL_GLFUNCTIONINSTALL(glUseProgram, PFNGLUSEPROGRAMPROC)
			PXGL_GLFUNCTIONINSTALL(glGenFramebuffers, PFNGLGENFRAMEBUFFERSPROC)
			PXGL_GLFUNCTIONINSTALL(glBindFramebuffer, PFNGLBINDFRAMEBUFFERPROC)
			PXGL_GLFUNCTIONINSTALL(glFramebufferTexture, PFNGLFRAMEBUFFERTEXTUREPROC)
			PXGL_GLFUNCTIONINSTALL(glDrawBuffers, PFNGLDRAWBUFFERSPROC)
			PXGL_GLFUNCTIONINSTALL(glCheckFramebufferStatus, PFNGLCHECKFRAMEBUFFERSTATUSPROC)
			PXGL_GLFUNCTIONINSTALL(glClearBufferfv, PFNGLCLEARBUFFERFVPROC)
			PXGL_GLFUNCTIONINSTALL(glBlendEquation, PFNGLBLENDEQUATIONPROC)

			PXGL_GLFUNCTIONINSTALL(glUniformMatrix4dv, PFNGLUNIFORMMATRIX4DVPROC)
			PXGL_GLFUNCTIONINSTALL(glUniformMatrix4fv, PFNGLUNIFORMMATRIX4FVPROC)
			PXGL_GLFUNCTIONINSTALL(glUniform4f, PFNGLUNIFORM4FPROC)
			PXGL_GLFUNCTIONINSTALL(glUniform3f, PFNGLUNIFORM3FPROC)
			PXGL_GLFUNCTIONINSTALL(glUniform2f, PFNGLUNIFORM2FPROC)
			PXGL_GLFUNCTIONINSTALL(glUniform1i, PFNGLUNIFORM1IPROC)
			PXGL_GLFUNCTIONINSTALL(glUniform1f, PFNGLUNIFORM1FPROC)
			PXGL_GLFUNCTIONINSTALL(glUniform3fv, PFNGLUNIFORM3FVPROC)
			PXGL_GLFUNCTIONINSTALL(glGetUniformLocation, PFNGLGETUNIFORMLOCATIONPROC)

			PXGL_GLFUNCTIONINSTALL(glBufferSubData, PFNGLBUFFERSUBDATAPROC)
			PXGL_GLFUNCTIONINSTALL(glBindBufferBase, PFNGLBINDBUFFERBASEPROC)
			PXGL_GLFUNCTIONINSTALL(glActiveTexture, PFNGLACTIVETEXTUREPROC)

			PXGL_GLFUNCTIONINSTALL(glDebugMessageCallback, PFNGLDEBUGMESSAGECALLBACKPROC)

			PXGL_GLFUNCTIONINSTALL(glGetIntegeri_v, PFNGLGETINTEGERI_VPROC)
			PXGL_GLFUNCTIONINSTALL(glTexBuffer, PFNGLTEXBUFFERPROC)
			PXGL_GLFUNCTIONINSTALL(glGetBufferSubData, PFNGLGETBUFFERSUBDATAPROC)
			PXGL_GLFUNCTIONINSTALL(glDispatchCompute, PFNGLDISPATCHCOMPUTEPROC)
			PXGL_GLFUNCTIONINSTALL(glMemoryBarrier, PFNGLMEMORYBARRIERPROC)
			PXGL_GLFUNCTIONINSTALL(glBindImageTexture, PFNGLBINDIMAGETEXTUREPROC)
			PXGL_GLFUNCTIONINSTALL(glDeleteFramebuffers, PFNGLDELETEFRAMEBUFFERSPROC)

			PXGL_GLFUNCTIONINSTALL(glGetGraphicsResetStatus, PFNGLGETGRAPHICSRESETSTATUSPROC)
		}
	};
}

#endif // PXGL_GLFUNCTIONS_HPP

